ph-ee-engine:
  zeebe-cluster:
    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"
    
    elasticsearch:
      enabled: true
      replicas: 1
      minimumMasterNodes: 1

      # Shrink default JVM heap.
      esJavaOpts: "-Xmx128m -Xms128m"

      # Allocate smaller chunks of memory per pod.
      resources:
        requests:
          cpu: "100m"
          memory: "512M"
        limits:
          cpu: "1000m"
          memory: "512M"
      volumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi
    kibana:
      enabled: true

  zeebe-operate: 
    enabled: true

  elasticsearch:
    enabled: true
    replicas: 1

  kibana:
    enabled: true

  operations:
    enabled: true
   
  operationsMysql:
    mysqlRootPassword: "ethieTieCh8ahv"
    mysqlUser: "mifos"
    mysqlPassword: "password"
    mysqlDatabase: "tenants"
    initializationFiles:
      setup.sql: |-
        CREATE DATABASE ibank-usa;
        CREATE DATABASE ibank-india;
        GRANT ALL PRIVILEGES ON ibank-usa.* TO 'mifos';
        GRANT ALL PRIVILEGES ON ibank-india.* TO 'mifos';

  ph_ee_connector_ams_mifos:
    SPRING_PROFILES_ACTIVE: "fin12,bb"

  ph_ee_connector_mojaloop:
    SPRING_PROFILES_ACTIVE: "bb"

  ph_ee_connector_channel:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "channel.ibank.com"

  ph_ee_operations_app:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "ops.ibank.com"

  ph_ee_operations:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "ops.ibank.com"
    webhost: "ops-ui.ibank.com"

  ph_ee_connector_gsma:
    SPRING_PROFILES_ACTIVE: "bb"

  ph_ee_identity:
    hostname: "barebone-identity.mifos.io"
