ph-ee-engine:
  zeebe-cluster:
    clusterSize: "1"
    partitionCount: "1"
    replicationFactor: "1"
    
    elasticsearch:
      enabled: false
    kibana:
      enabled: false

  zeebe-operate: 
    enabled: false

  elasticsearch:
    enabled: true
    replicas: 1

  kibana:
    enabled: true

  operations:
    enabled: false

  ph_ee_connector_ams_mifos:
    SPRING_PROFILES_ACTIVE: "fin12,bb"

  ph_ee_connector_mojaloop:
    SPRING_PROFILES_ACTIVE: "bb"

  ph_ee_connector_channel:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "channel.ibank.com"

  ph_ee_operations_app:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "ops.ibank.com"

  ph_ee_operations:
    SPRING_PROFILES_ACTIVE: "bb"
    hostname: "ops.ibank.com"
    webhost: "ops-ui.ibank.com"

  ph_ee_connector_gsma:
    SPRING_PROFILES_ACTIVE: "bb"

  ph_ee_identity:
    hostname: "barebone-identity.mifos.io"
